sonar.projectKey=revisium_revisium-examples
sonar.organization=revisium
sonar.projectName=revisium-examples

sonar.sources=apps,docs,infrastructure,quickstarts,scripts,templates,.github,README.md,examples.json,package.json,eslint.config.mjs
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**,reports/**,dist/**,build/**,.git/**,package-lock.json

sonar.eslint.reportPaths=reports/eslint-report.json
