replicaCount: 1

image:
  repository: redis
  tag: "7.4-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 50m
    memory: 128Mi

persistence:
  enabled: true
  size: 1Gi
  storageClass: "standard"
  accessMode: ReadWriteOnce

redis:
  config:
    maxmemory: "100mb"
    maxmemoryPolicy: "noeviction"
    save: "900 1"
